### ISSUE TITLE
how can i point this analyser to an existing local server?

### ISSUE THREAD

**Issue by ksaitor** [maddevsio/seo-analyzer#2]
For example i have a local CRA or Next.js app running on `localhost:3000`. How can i point this tool to analyse `localhost:3000` ? 

p.s.
Also, would be cool if this could be part of a test suite, so that if something breaks, whole build fails.

**Comment by denisoed** [comment]
Hi @ksaitor! 
Thanks for the feedback ;)

Unfortunately, the analyzer does not yet know how to work with localhost. But we will definitely add this functionality. Stay tuned for more updates.

Please use the .outputConsole function to abort the build process if the CEO analyzer finds errors.

**Comment by oh-cactus** [comment]
> For example i have a local CRA or Next.js app running on `localhost:3000`. How can i point this tool to analyse `localhost:3000` ?
> 
> p.s. Also, would be cool if this could be part of a test suite, so that if something breaks, whole build fails.

This update is now avaliable!
You can use `.inputNextJs(3000)` rule for analyze Next.js app on `localhost:3000`.
Also you can run seo-analyzer on pre-push or pre-commit. [Read more](https://maddevs.io/insights/blog/seo-analyzer/#running-in-pre-push-or-pre-commit)
